### ISSUE TITLE
unable to set initial date for calendar

### ISSUE THREAD

**Issue by Kehet** [diosney/angular-bootstrap-datetimepicker-directive#9]
I'm trying to set initial value for field, so user can edit existing data in my app.

Here is my html

``` html
<div class="input-group date" 
     data-datetimepicker="" 
     data-datetimepicker-options="{{ datetimepicker_options }}">

    <input type="text" class="form-control"
           placeholder=""
           name="start_at"
           id="start_at"
           ng-model="event.start_at" />

    <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
    </span>
</div>
```

And here js in controller

``` js
$scope.event = {
    start_at: moment('2013-12-24 09:00:00')
};

$scope.datetimepicker_options = {
    defaultDate: $scope.event.start_at
};
```

This shows correct date (without formatting) on text field when page is loaded. However datetimepicker have no idea it should have some specific day selected.

Am I missing some config value or just misunderstood how this should work?

**Comment by planting** [comment]
@Kehet I have the same issue, have you got it to work?

**Comment by Kehet** [comment]
@planting I had to do monkey patch and unfortunately I don't have access to that code any more

**Comment by diosney** [comment]
I'm quite busy right now and can't spend lot of time on this, any working PR will be welcome :)

Thanks
